#spring:
#  datasource:
#    url: jdbc:postgresql://13.48.128.129:5432/hms_db
#    username: hms_user
#    password: hms_password
spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/hms_db
    url: jdbc:postgresql://13.48.128.129:5432/hms_db
    username: hms_user
    password: hms_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true

# Swagger UI / OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
#    tagsSorter: alpha
#    tryItOutEnabled: true
#    filter: true
#    syntax-highlight:
#      activated: true

# Logging levels
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.jdbc.core.JdbcTemplate: OFF
    org.springframework.jdbc.core.StatementCreatorUtils: OFF
