#spring:
#  datasource:
#    url: jdbc:postgresql://13.48.128.129:5432/hms_db
#    username: hms_user
#    password: hms_password
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/hms_db_v2
#    username: hms_user
#    password: hms_password
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hms_db_v2}
    username: ${SPRING_DATASOURCE_USERNAME:hms_user}
    password: ${SPRING_DATASOURCE_PASSWORD:hms_password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
