spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hms
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
