package housingManagment.hms.enums.userEnum;

public enum StudentRole {
    MASTER_STUDENT_1_Y,
    MASTER_STUDENT_2_Y,
    BACHELOR_DEGREE_1_Y,
    BACHELOR_DEGREE_2_Y,
    BACHELOR_DEGREE_3_Y,
    BACHELOR_DEGREE_4_Y,
    BACHELOR_DEGREE_5_Y,
    NUFYP,
    DOCTORAL_STUDENT_1_Y,
    DOCTORAL_STUDENT_2_Y,
    DOCTORAL_STUDENT_3_Y,
    DOCTORAL_STUDENT_4_Y,
    DOCTORAL_STUDENT_5_Y,
    EXCHANGE_STUDENT,
    GUEST_STUDENT,
    ALUMNI
}
