version: '3.8'

services:
  postgres:
    container_name: hms_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: hms_user
      POSTGRES_PASSWORD: hms_password
      POSTGRES_DB: hms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hms_user -d hms_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hms_network

volumes:
  postgres_data:
    name: hms_postgres_data

networks:
  hms_network:
    name: hms_network